name: tests

on:
  push:
    branches: [ "dev", "master" ]
  pull_request:
    branches: [ "dev", "master" ]

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    runs-on: ubuntu-22.04
    container: osgeo/grass-gis:releasebranch_8_4-ubuntu
    steps:
    - uses: actions/checkout@v4
    # - name: Set up Python ${{ matrix.python-version }}
    #   uses: actions/setup-python@v5
    #   with:
    #     python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        apt update
        apt install -y clang build-essential libomp-dev nodejs

    - name: Install PDM and uv
      run: |
        curl -sSLO https://pdm-project.org/install-pdm.py
        curl -sSL https://pdm-project.org/install-pdm.py.sha256 | shasum -a 256 -c -
        python3 install-pdm.py --path /usr/local
        curl -LsSf https://astral.sh/uv/install.sh | sh
        pdm config use_uv true
        pdm use ${{ matrix.python-version }}

    - name: Build and install
      run: |
        echo $PATH
        pdm install

    - name: Test with pytest
      run: |
        pdm run pytest --cov=src --forked --junitxml=junit/test-results.xml --cov-report=xml --cov-report=html tests/test_infiltration.py

    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-${{ matrix.python-version }}
        path: |
          htmlcov/
          coverage.xml
