name: tests

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]

    runs-on: ubuntu-latest
    container: osgeo/grass-gis:releasebranch_8_4-ubuntu
    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y ca-certificates git-lfs

    - uses: actions/checkout@v7
      with:
        lfs: true

    - name: Install uv and Python
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        $HOME/.local/bin/uv python install ${{ matrix.python-version }}

    - name: Pytest
      run: |
        $HOME/.local/bin/uv run --all-extras --python ${{ matrix.python-version }} pytest --cov=src --cov-report= --junitxml=junit/test-cli-results.xml tests/cli tests/test_grass_session.py
        for test_file in tests/grass/test_*.py; do
          $HOME/.local/bin/uv run --all-extras --python ${{ matrix.python-version }} pytest --cov=src --cov-append --cov-report= --junitxml="junit/$(basename "$test_file" .py)-results.xml" "$test_file"
        done
        $HOME/.local/bin/uv run --all-extras --python ${{ matrix.python-version }} coverage xml
        $HOME/.local/bin/uv run --all-extras --python ${{ matrix.python-version }} coverage html

    - name: Upload coverage
      uses: actions/upload-artifact@v7
      with:
        name: coverage-report-${{ matrix.python-version }}
        path: |
          htmlcov/
          coverage.xml
